# https://docs.streamlit.io/library/advanced-features/configuration

[server]
port = 8501
enableXsrfProtection = true

[client]
toolbarMode = "minimal"

[theme]
base = 'light'
#primaryColor = '#7792E3'
#backgroundColor = '#273346'
#secondaryBackgroundColor = '#B9F1C0'
#textColor = '#FFFFFF'
font = 'sans serif'